import {
  OrderStatus,
  PaymentGateway,
  PaymentStatus,
  Prisma,
  Role,
} from "@/generated/prisma/client.js";
import {
  PaymentCreateInput,
  UserCreateInput,
} from "@/generated/prisma/models.js";

export const userData: UserCreateInput[] = [
  {
    email: "admin@email.com",
    name: "Admin User",
    password: "Admin@123",
    role: Role.ADMIN,
  },
  {
    email: "user1@email.com",
    name: "User One",
    password: "User1@123",
    role: Role.SELLER,
  },
  {
    email: "user2@email.com",
    name: "User Two",
    password: "User2@123",
    role: Role.SELLER,
  },
  {
    email: "user3@email.com",
    name: "User Three",
    password: "User3@123",
    role: Role.SELLER,
  },
  {
    email: "user4@email.com",
    name: "User Four",
    password: "User4@123",
    role: Role.SELLER,
  },
  {
    email: "user5@email.com",
    name: "User Five",
    password: "User5@123",
    role: Role.SELLER,
  },
  {
    email: "user6@email.com",
    name: "User Six",
    password: "User6@123",
    role: Role.SELLER,
  },
  {
    email: "user7@email.com",
    name: "User Seven",
    password: "User7@123",
    role: Role.SELLER,
  },
  {
    email: "user8@email.com",
    name: "User Eight",
    password: "User8@123",
    role: Role.USER,
  },
  {
    email: "user9@email.com",
    name: "User Nine",
    password: "User9@123",
  },
  {
    email: "user10@email.com",
    name: "User Ten",
    password: "User10@123",
  },
  {
    email: "user11@email.com",
    name: "User Eleven",
    password: "User11@123",
  },
];

export const productData: Prisma.ProductCreateInput[] = [
  {
    name: "Wireless Headphones",
    price: 7999,
    description: "High-quality wireless headphones with noise cancellation",
    category: "ELECTRONICS",
    quantity: 5,
    user: { connect: { email: "user1@email.com" } },
    images: [
      "32340.webp",
      "618271.webp",
      "426537.webp",
      "538557.webp",
      "346744.webp",
    ],
  },
  {
    name: "Smart Watch",
    price: 15999,
    description: "Fitness tracker with heart rate monitor and GPS",
    category: "ELECTRONICS",
    quantity: 50,
    user: { connect: { email: "user2@email.com" } },
    images: [
      "551769.webp",
      "337205.webp",
      "199221.webp",
      "195389.webp",
      "467710.webp",
      "764666.webp",
      "490587.webp",
    ],
  },
  {
    name: "Cotton T-Shirt",
    price: 1299,
    description: "Comfortable 100% cotton t-shirt in multiple colors",
    category: "FASHION",
    quantity: 3,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "Running Shoes",
    price: 8999,
    description: "Lightweight running shoes with superior cushioning",
    category: "FASHION",
    quantity: 6,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Coffee Maker",
    price: 5499,
    description: "Programmable coffee maker with thermal carafe",
    category: "HOME",
    quantity: 24,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "LED Desk Lamp",
    price: 2999,
    description: "Adjustable LED desk lamp with touch control",
    category: "HOME",
    quantity: 1,
    user: { connect: { email: "user6@email.com" } },
  },
  {
    name: "Building Blocks Set",
    price: 4599,
    description: "500-piece building blocks set for creative play",
    category: "TOYS",
    quantity: 7,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "Remote Control Car",
    price: 3499,
    description: "Fast RC car with rechargeable battery",
    category: "TOYS",
    quantity: 13,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "Programming Guide",
    price: 3999,
    description: "Comprehensive guide to modern web development",
    category: "BOOKS",
    quantity: 67,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Cookbook Collection",
    price: 2499,
    description: "100 easy recipes for everyday cooking",
    category: "BOOKS",
    quantity: 8,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "Organic Honey",
    price: 899,
    description: "Pure organic honey from local farms",
    category: "FOOD",
    quantity: 9,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Green Tea Pack",
    price: 699,
    description: "Premium green tea leaves, 100g pack",
    category: "FOOD",
    quantity: 14,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "Portable Bluetooth Speaker",
    price: 3299,
    description:
      "Compact Bluetooth speaker with deep bass and long battery life",
    category: "ELECTRONICS",
    quantity: 18,
    user: { connect: { email: "user6@email.com" } },
  },
  {
    name: "Noise Cancelling Earbuds",
    price: 6499,
    description: "In-ear earbuds with active noise cancellation",
    category: "ELECTRONICS",
    quantity: 22,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "USB-C Power Bank",
    price: 2799,
    description: "10000mAh fast-charging power bank with USB-C",
    category: "ELECTRONICS",
    quantity: 31,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "4K Action Camera",
    price: 10999,
    description: "Rugged 4K action camera with waterproof case",
    category: "ELECTRONICS",
    quantity: 10,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Gaming Keyboard",
    price: 4599,
    description: "Mechanical keyboard with RGB backlight",
    category: "ELECTRONICS",
    quantity: 16,
    user: { connect: { email: "user3@email.com" } },
    images: ["405832.webp", "309091.webp", "726172.webp", "731486.webp"],
  },
  {
    name: "Casual Denim Jacket",
    price: 3999,
    description: "Classic fit denim jacket for everyday wear",
    category: "FASHION",
    quantity: 12,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Yoga Mat Pro",
    price: 1899,
    description: "Non-slip yoga mat with extra cushioning",
    category: "FASHION",
    quantity: 27,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "Leather Wallet",
    price: 2199,
    description: "Genuine leather wallet with RFID blocking",
    category: "FASHION",
    quantity: 20,
    user: { connect: { email: "user6@email.com" } },
  },
  {
    name: "Winter Hoodie",
    price: 2699,
    description: "Warm fleece-lined hoodie with front pocket",
    category: "FASHION",
    quantity: 14,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "Sports Cap",
    price: 999,
    description: "Breathable sports cap with adjustable strap",
    category: "FASHION",
    quantity: 34,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "Air Fryer",
    price: 7999,
    description: "Healthy air fryer with digital temperature control",
    category: "HOME",
    quantity: 15,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Vacuum Cleaner",
    price: 12999,
    description: "Bagless vacuum cleaner with strong suction power",
    category: "HOME",
    quantity: 9,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "Ceramic Dinner Set",
    price: 4999,
    description: "16-piece ceramic dinnerware set",
    category: "HOME",
    quantity: 11,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Memory Foam Pillow",
    price: 2399,
    description: "Ergonomic memory foam pillow for neck support",
    category: "HOME",
    quantity: 26,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "Wall Art Frame",
    price: 1799,
    description: "Modern wall art frame for living room decor",
    category: "HOME",
    quantity: 17,
    user: { connect: { email: "user6@email.com" } },
  },
  {
    name: "Puzzle Cube Kit",
    price: 1299,
    description: "Set of speed cubes for puzzle enthusiasts",
    category: "TOYS",
    quantity: 29,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "Board Game Deluxe",
    price: 2899,
    description: "Family board game with deluxe components",
    category: "TOYS",
    quantity: 13,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "Kids Drawing Tablet",
    price: 1999,
    description: "Reusable LCD drawing tablet for kids",
    category: "TOYS",
    quantity: 23,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Robot Toy Kit",
    price: 3799,
    description: "DIY robot toy kit for STEM learning",
    category: "TOYS",
    quantity: 19,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "Plush Teddy Bear",
    price: 1499,
    description: "Soft plush teddy bear suitable for all ages",
    category: "TOYS",
    quantity: 32,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Mystery Novel Box Set",
    price: 3599,
    description: "Collection of bestselling mystery novels",
    category: "BOOKS",
    quantity: 18,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "Data Science Handbook",
    price: 4299,
    description: "Practical handbook for data science workflows",
    category: "BOOKS",
    quantity: 21,
    user: { connect: { email: "user6@email.com" } },
  },
  {
    name: "Travel Photography Guide",
    price: 2699,
    description: "Guide to composition and lighting while traveling",
    category: "BOOKS",
    quantity: 16,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "Children's Story Collection",
    price: 2199,
    description: "Illustrated bedtime stories for children",
    category: "BOOKS",
    quantity: 24,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "Language Learning Workbook",
    price: 1499,
    description: "Beginner workbook for daily language practice",
    category: "BOOKS",
    quantity: 28,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Organic Almonds Pack",
    price: 1199,
    description: "Roasted organic almonds, 500g pack",
    category: "FOOD",
    quantity: 35,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "Dark Chocolate Bar Pack",
    price: 899,
    description: "70% dark chocolate assorted bar pack",
    category: "FOOD",
    quantity: 40,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Instant Oats Jar",
    price: 699,
    description: "High-fiber instant oats jar for quick breakfast",
    category: "FOOD",
    quantity: 37,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "Spicy Peanut Mix",
    price: 599,
    description: "Crunchy spicy peanut snack mix",
    category: "FOOD",
    quantity: 42,
    user: { connect: { email: "user6@email.com" } },
  },
  {
    name: "Cold Brew Coffee Beans",
    price: 1399,
    description: "Medium roast coffee beans for cold brew",
    category: "FOOD",
    quantity: 30,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "Smart Home Hub",
    price: 9999,
    description: "Voice-enabled smart home control hub",
    category: "ELECTRONICS",
    quantity: 8,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "Mechanical Mouse",
    price: 2499,
    description: "High-precision gaming mouse with programmable buttons",
    category: "ELECTRONICS",
    quantity: 19,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Wireless Charger Pad",
    price: 1599,
    description: "Fast wireless charging pad with overheat protection",
    category: "ELECTRONICS",
    quantity: 27,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "HDMI Adapter Kit",
    price: 1299,
    description: "Multi-port HDMI adapter for laptops and tablets",
    category: "ELECTRONICS",
    quantity: 25,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Tablet Stand",
    price: 1099,
    description: "Foldable aluminum stand for tablets and phones",
    category: "ELECTRONICS",
    quantity: 33,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "Running Shorts",
    price: 1499,
    description: "Lightweight running shorts with moisture-wicking fabric",
    category: "FASHION",
    quantity: 26,
    user: { connect: { email: "user6@email.com" } },
  },
  {
    name: "Training Gloves",
    price: 1199,
    description: "Breathable gloves for gym and fitness training",
    category: "FASHION",
    quantity: 22,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "Polarized Sunglasses",
    price: 1999,
    description: "UV-protected polarized sunglasses",
    category: "FASHION",
    quantity: 18,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "Canvas Backpack",
    price: 2799,
    description: "Durable canvas backpack with laptop compartment",
    category: "FASHION",
    quantity: 15,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Stainless Steel Water Bottle",
    price: 899,
    description: "Insulated stainless steel bottle, 750ml",
    category: "FASHION",
    quantity: 36,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "Electric Kettle",
    price: 2599,
    description: "1.7L electric kettle with auto shut-off",
    category: "HOME",
    quantity: 20,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Non-Stick Pan Set",
    price: 4199,
    description: "Three-piece non-stick cookware pan set",
    category: "HOME",
    quantity: 14,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "Bamboo Storage Box",
    price: 1699,
    description: "Eco-friendly bamboo storage organizer",
    category: "HOME",
    quantity: 23,
    user: { connect: { email: "user6@email.com" } },
  },
  {
    name: "Aromatherapy Diffuser",
    price: 2299,
    description: "Ultrasonic aroma diffuser with soft night light",
    category: "HOME",
    quantity: 17,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "Desk Organizer Tray",
    price: 999,
    description: "Multi-compartment tray for desk essentials",
    category: "HOME",
    quantity: 31,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "Strategy Card Game",
    price: 1899,
    description: "Competitive strategy card game for 2-6 players",
    category: "TOYS",
    quantity: 21,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Wooden Train Set",
    price: 3199,
    description: "Classic wooden train set with tracks and accessories",
    category: "TOYS",
    quantity: 12,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "Science Experiment Kit",
    price: 2799,
    description: "Hands-on science experiments kit for children",
    category: "TOYS",
    quantity: 18,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Coloring Pencil Set",
    price: 799,
    description: "48-color premium coloring pencil set",
    category: "TOYS",
    quantity: 28,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "Mini Drone",
    price: 6999,
    description: "Compact mini drone with HD camera",
    category: "TOYS",
    quantity: 9,
    user: { connect: { email: "user6@email.com" } },
  },
  // --- batch 2 additions ---
  {
    name: "Smart LED Bulb Pack",
    price: 1299,
    description: "Wi-Fi enabled colour-changing LED bulbs, pack of 4",
    category: "ELECTRONICS",
    quantity: 38,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "Laptop Cooling Pad",
    price: 1899,
    description: "Dual-fan USB laptop cooling pad with ergonomic stand",
    category: "ELECTRONICS",
    quantity: 22,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "Digital Drawing Pen Tablet",
    price: 8999,
    description: "Pressure-sensitive pen tablet for digital illustration",
    category: "ELECTRONICS",
    quantity: 11,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Portable Solar Charger",
    price: 3499,
    description: "Foldable solar panel charger for outdoor use",
    category: "ELECTRONICS",
    quantity: 16,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "True Wireless Earphones",
    price: 4299,
    description: "Sweat-proof true wireless earphones with charging case",
    category: "ELECTRONICS",
    quantity: 27,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Smart Doorbell Camera",
    price: 7499,
    description: "1080p Wi-Fi doorbell with motion detection and night vision",
    category: "ELECTRONICS",
    quantity: 14,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "USB Hub 7-Port",
    price: 1599,
    description: "Compact 7-port USB 3.0 hub with individual power switches",
    category: "ELECTRONICS",
    quantity: 30,
    user: { connect: { email: "user6@email.com" } },
  },
  {
    name: "Webcam HD 1080p",
    price: 3999,
    description: "Full HD webcam with built-in microphone for video calls",
    category: "ELECTRONICS",
    quantity: 19,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "External SSD 1TB",
    price: 9999,
    description: "Compact external SSD with USB-C, up to 1050 MB/s",
    category: "ELECTRONICS",
    quantity: 12,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "Ergonomic Office Chair",
    price: 18999,
    description: "Lumbar-support mesh office chair with adjustable armrests",
    category: "HOME",
    quantity: 7,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Stainless Steel Thermos",
    price: 1299,
    description: "Double-wall vacuum thermos, 500ml, keeps hot 12h",
    category: "HOME",
    quantity: 34,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "Indoor Plant Grow Light",
    price: 2799,
    description: "Full-spectrum LED grow light for indoor plants",
    category: "HOME",
    quantity: 20,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Shower Filter",
    price: 1499,
    description: "Chlorine-removal shower filter for soft water",
    category: "HOME",
    quantity: 26,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "Cast Iron Skillet",
    price: 3799,
    description: "Pre-seasoned cast iron skillet, 10-inch",
    category: "HOME",
    quantity: 18,
    user: { connect: { email: "user6@email.com" } },
  },
  {
    name: "Wall-Mount Key Holder",
    price: 799,
    description: "Decorative wall-mount key and mail organizer",
    category: "HOME",
    quantity: 42,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "Blackout Curtain Pair",
    price: 2599,
    description: "Room-darkening blackout curtains, 52x84 inches",
    category: "HOME",
    quantity: 23,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "Bamboo Cutting Board",
    price: 1199,
    description: "Extra-large bamboo cutting board with juice groove",
    category: "HOME",
    quantity: 31,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Electric Toothbrush",
    price: 2299,
    description: "Rechargeable electric toothbrush with 3 brush heads",
    category: "HOME",
    quantity: 25,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "Hanging Dish Rack",
    price: 1699,
    description: "Over-sink stainless steel hanging dish drying rack",
    category: "HOME",
    quantity: 17,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Slim Fit Chino Pants",
    price: 2299,
    description: "Stretch slim-fit chino trousers in neutral tones",
    category: "FASHION",
    quantity: 20,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "Formal Oxford Shoes",
    price: 5999,
    description: "Classic leather Oxford dress shoes",
    category: "FASHION",
    quantity: 14,
    user: { connect: { email: "user6@email.com" } },
  },
  {
    name: "Woolen Scarf",
    price: 1199,
    description: "Soft merino wool scarf in solid colour",
    category: "FASHION",
    quantity: 28,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "Athletic Compression Socks",
    price: 799,
    description: "Graduated compression sports socks, 3-pair pack",
    category: "FASHION",
    quantity: 39,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "Slim Leather Belt",
    price: 1399,
    description: "Genuine leather belt with pin-buckle closure",
    category: "FASHION",
    quantity: 24,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Floral Summer Dress",
    price: 2799,
    description: "Lightweight floral print midi dress",
    category: "FASHION",
    quantity: 18,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "Knitted Beanie Hat",
    price: 699,
    description: "Warm ribbed-knit winter beanie hat",
    category: "FASHION",
    quantity: 33,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Self-Help Bestseller Pack",
    price: 2999,
    description: "Bundle of 3 bestselling self-help books",
    category: "BOOKS",
    quantity: 22,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "History of Ancient Civilizations",
    price: 3499,
    description: "Illustrated hardcover on ancient world history",
    category: "BOOKS",
    quantity: 15,
    user: { connect: { email: "user6@email.com" } },
  },
  {
    name: "Personal Finance Guide",
    price: 1999,
    description: "Step-by-step guide to budgeting and investing",
    category: "BOOKS",
    quantity: 27,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "Science Fiction Anthology",
    price: 2799,
    description: "Curated short story anthology from top sci-fi authors",
    category: "BOOKS",
    quantity: 19,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "Yoga & Meditation Handbook",
    price: 1699,
    description: "Beginner guide to yoga poses and mindfulness",
    category: "BOOKS",
    quantity: 24,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Graphic Novel Trilogy Set",
    price: 4299,
    description: "Complete three-volume graphic novel set",
    category: "BOOKS",
    quantity: 13,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "Spice Gift Box",
    price: 1499,
    description: "Curated set of 10 exotic cooking spices",
    category: "FOOD",
    quantity: 36,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Dried Mango Slices",
    price: 899,
    description: "No-sugar-added dried mango slices, 200g",
    category: "FOOD",
    quantity: 44,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "Protein Bar Pack",
    price: 1799,
    description: "High-protein snack bars, chocolate flavour, 12-pack",
    category: "FOOD",
    quantity: 40,
    user: { connect: { email: "user6@email.com" } },
  },
  {
    name: "Himalayan Pink Salt",
    price: 599,
    description: "Fine-grain Himalayan pink salt in resealable bag",
    category: "FOOD",
    quantity: 52,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "Olive Oil Extra Virgin",
    price: 1299,
    description: "Cold-pressed extra virgin olive oil, 500ml bottle",
    category: "FOOD",
    quantity: 38,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "Herbal Tea Assortment",
    price: 999,
    description: "20-bag assorted herbal tea variety pack",
    category: "FOOD",
    quantity: 47,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Cashew Butter Jar",
    price: 1699,
    description: "Smooth natural cashew butter, no added oils",
    category: "FOOD",
    quantity: 29,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "RC Stunt Drone",
    price: 5499,
    description: "360° flip stunt drone with LED lights",
    category: "TOYS",
    quantity: 16,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Magnetic Fishing Game",
    price: 999,
    description: "Classic magnetic fishing game for toddlers",
    category: "TOYS",
    quantity: 31,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "Foam Play Mat Set",
    price: 2299,
    description: "Interlocking foam floor tiles for kids play area",
    category: "TOYS",
    quantity: 22,
    user: { connect: { email: "user6@email.com" } },
  },
  {
    name: "Educational Globe",
    price: 3199,
    description: "Interactive illuminated educational globe",
    category: "TOYS",
    quantity: 14,
    user: { connect: { email: "user7@email.com" } },
  },
  {
    name: "Paint-by-Number Kit",
    price: 1599,
    description: "Adult acrylic paint-by-number canvas kit",
    category: "TOYS",
    quantity: 26,
    user: { connect: { email: "user1@email.com" } },
  },
  {
    name: "Chess Set Deluxe",
    price: 3599,
    description: "Handcrafted wooden chess set with storage board",
    category: "TOYS",
    quantity: 18,
    user: { connect: { email: "user2@email.com" } },
  },
  {
    name: "Mini Basketball Hoop",
    price: 2199,
    description: "Over-door mini basketball hoop set with balls",
    category: "TOYS",
    quantity: 21,
    user: { connect: { email: "user3@email.com" } },
  },
  {
    name: "Smart Scale Body Fat",
    price: 2999,
    description: "Bluetooth smart scale with body composition analysis",
    category: "ELECTRONICS",
    quantity: 20,
    user: { connect: { email: "user4@email.com" } },
  },
  {
    name: "Projector Mini Portable",
    price: 14999,
    description: "1080p mini portable projector with built-in speaker",
    category: "ELECTRONICS",
    quantity: 8,
    user: { connect: { email: "user5@email.com" } },
  },
  {
    name: "VR Headset Lite",
    price: 11999,
    description: "Standalone VR headset with 3 DOF motion tracking",
    category: "ELECTRONICS",
    quantity: 6,
    user: { connect: { email: "user6@email.com" } },
    images: ["552564.webp", "921963.webp"],
  },
];

export const cartData: {
  email: string;
  products: { email: string; quantity: number }[];
}[] = [
  {
    email: userData[1].email,
    products: [
      { email: userData[7].email, quantity: 2 }, // product created by user1
      { email: userData[3].email, quantity: 2 },
      { email: userData[5].email, quantity: 5 },
      { email: userData[2].email, quantity: 3 },
    ],
  },
  {
    email: userData[2].email,
    products: [
      { email: userData[1].email, quantity: 2 }, // product created by user1
      { email: userData[3].email, quantity: 2 },
      { email: userData[5].email, quantity: 5 },
      { email: userData[2].email, quantity: 3 },
    ],
  },
  {
    email: userData[3].email,
    products: [
      { email: userData[7].email, quantity: 2 }, // product created by user1
      { email: userData[1].email, quantity: 2 },
      { email: userData[5].email, quantity: 5 },
      { email: userData[2].email, quantity: 3 },
    ],
  },
  {
    email: userData[8].email,
    products: [
      { email: userData[1].email, quantity: 2 }, // product created by user1
      { email: userData[2].email, quantity: 1 },
    ],
  },
  {
    email: userData[9].email,
    products: [{ email: userData[3].email, quantity: 5 }],
  },
];

// Payment of Orders
export const paymentData: PaymentCreateInput[] = [
  {
    pidx: "WSvpb9DRigUTY2QJPnouch",
    date: new Date("2025-04-24T10:30:00Z"),
    geteway: PaymentGateway.KHALTI,
    status: PaymentStatus.SUCCESS,
  },
  {
    pidx: "WSvpb9DRigUTY2QJPnoudh",
    date: new Date("2025-12-02T12:01:00Z"),
    geteway: PaymentGateway.PAYPAL,
    status: PaymentStatus.SUCCESS,
  },
  {
    pidx: "WSvpb9DRigUTY2QJPnoioh",
    date: new Date("2026-01-23T01:03:00Z"),
    geteway: PaymentGateway.PAYPAL,
    status: PaymentStatus.SUCCESS,
  },
  {
    pidx: "WSvpb9DRiaUTY2HJPnouch",
    date: new Date("2024-11-30T12:01:00Z"),
    geteway: PaymentGateway.PAYPAL,
    status: PaymentStatus.SUCCESS,
  },
  {
    pidx: "WSvpb9DkbgUTY2HJPnouch",
    date: new Date("2026-02-12T12:01:00Z"),
    geteway: PaymentGateway.PAYPAL,
    status: PaymentStatus.SUCCESS,
  },
];

//  orders / orderItems seed
export const orderData: {
  email: string;
  items: { productName: string; quantity: number; price: number }[];
  status: OrderStatus;
  payment?: PaymentCreateInput;
}[] = [
  {
    email: userData[8].email,
    items: [
      {
        productName: productData[0].name,
        quantity: 1,
        price: productData[0].price,
      },
      {
        productName: productData[1].name,
        quantity: 1,
        price: productData[1].price,
      },
      {
        productName: productData[11].name,
        quantity: 2,
        price: productData[11].price,
      },
    ],
    status: OrderStatus.SHIPPING,
    payment: paymentData.at(0),
  },
  {
    email: userData[8].email,
    items: [
      {
        productName: productData[0].name,
        quantity: 1,
        price: productData[0].price,
      },
      {
        productName: productData[1].name,
        quantity: 1,
        price: productData[1].price,
      },
      {
        productName: productData[11].name,
        quantity: 2,
        price: productData[11].price,
      },
    ],
    status: OrderStatus.DECLINED,
  },
  {
    email: userData[2].email,
    items: [
      {
        productName: productData[3].name,
        quantity: 1,
        price: productData[3].price,
      },
      {
        productName: productData[10].name,
        quantity: 2,
        price: productData[10].price,
      },
    ],
    status: OrderStatus.CANCELLED,
  },
  {
    email: userData[9].email,
    items: [{ productName: "Cotton T-Shirt", quantity: 3, price: 1299 }],
    status: OrderStatus.PROCESSING,
    payment: paymentData.at(1),
  },
  {
    email: "user1@email.com",
    items: [
      { productName: "Wireless Headphones", quantity: 1, price: 7999 },
      { productName: "Green Tea Pack", quantity: 2, price: 699 },
    ],
    status: OrderStatus.PROCESSING,
    payment: paymentData.at(2),
  },
  {
    email: userData[7].email,
    items: [
      {
        productName: productData[3].name,
        quantity: 1,
        price: productData[3].price,
      },
      {
        productName: productData[9].name,
        quantity: 2,
        price: productData[9].price,
      },
      {
        productName: productData[4].name,
        quantity: 2,
        price: productData[4].price,
      },
    ],
    status: OrderStatus.SHIPPING,
    payment: paymentData.at(3),
  },
];
